### ISSUE TITLE
Add support for wordpress-generated embeds in excerpt

### ISSUE THREAD

**Issue by ebf2** [scholarslab/ivanhoe#131]
Wordpress generates embed code for youtube videos if you just reference the url.  The player only get displayed on the post content and not the excerpt.

Possible solution: http://spruce.it/noise/add-youtube-videos-other-media-embeds-to-the-wordpress-excerpt/

**Comment by csbailey5t** [comment]
Yes and no. If you use the "Add Media" button, then "Insert from URL," the video embed will not be shown in the excerpt. If you just get the embed code directly from youtube, then paste that in the "text" tab of the editor, then the video embed will show in the excerpt due to the crazy regex. This is quite strange, because in both cases, there is an iframe embedded, and the regex should pick up the iframe. The generated code actually looks identical. 

WP uses an embed shortcode to generate the iframe and whatnot from the youtube URL, whereas otherwise you paste the iframe code directly into the "text" tab. Could there be an issue with the timing, such that the regex searches the post for an iframe before WP generates the code with its shortcode?

**Comment by csbailey5t** [comment]
Issue is more likely related to the fact that WP strips out shortcodes with both the_excerpt and get_the_excerpt. Should be able to fix this by adding a filter on get_the_excerpt, which we use in single-ivanhoe_game.php to grab the excerpt before passing it to the media regex.
