### ISSUE TITLE
Style pagination on archive-ivanhoe_game page

### ISSUE THREAD

**Issue by csbailey5t** [scholarslab/ivanhoe#255]
We need to style the pagination

**Comment by jng3au** [comment]
apply infinite scroll to the game archive page

**Comment by clioweb** [comment]
I'd recommend just styling the pagination for this, unless work is already underway. Infinite scroll on a single game page is somewhat necessary, at least as we currently have it coded, to respond to multiple moves. Since there's no such need on the games browse, I'm not sure infinite scroll is necessary. Besides, I suspect there will be far more moves on a game than games themselves.

**Comment by jng3au** [comment]
I took a look at this yesterday and completely agree. The pagination is fixed on my local branch. Planning to come in today to make sure I did it correctly before merging it into develop.

**Comment by csbailey5t** [comment]
I don't think we'll often run into needing the pagination on the archive-ivanhoe_game view, but I think it is nice to keep it more consistent and use infinite scroll. It's also a trivial, one-minute fix (I have it working on a local branch). The other option would be to set the loop to just show all games.

**Comment by jng3au** [comment]
Implement infinite scroll for consistency in bfc167f189031a364e2a5d1f301ed01727a47e09
