### ISSUE TITLE
ivanhoe-staging.herokuapp.com shutdown

### ISSUE THREAD

**Issue by erochest** [scholarslab/ivanhoe#277]
The Ivanhoe staging app on Heroku uses the Mandrake module to handle email services (signing people up and that kind of thing). As far as I know, no one is using this staging site, and the code is a bit behind the code here in github. Because of that, I don't see any reason to transfer to a new service, and instead want to back up the database and put the site permanently into maintenance mode.

If anyone has any objections, they need to speak up in the new few days. If I don't hear anything, I'll turn it off Thursday morning.

Sorry for the late notice.

**Comment by af3pj** [comment]
Hi—

Will the backup be accessible? I used a couple of the games as examples in
a class and in a presentation this year, and was hoping to hold that option
open in the future.

—Andrew

**Comment by erochest** [comment]
So what I've done is gone ahead and removed that add-in. You should be able to still get to the sample games, although the site won't be able to send you email at all.

Let me know if it gives you any problems, though.
Eric

**Comment by jennifergrayburn** [comment]
Just a general question, since maintenance mode is a new term for me. What
will visitors see when it is in maintenance mode? Is the implication that
it is no longer functioning or will it look like we're making changes and
it might be back online some time? In a lot of my interviews, I've talked
about what I've started to call "digital clutter," and how it isn't always
clear what happens to a project after it receives some notice. I'm fine
taking it down for good,  but it'd be interesting to consider something of
a "digital obituary." Then if people encounter it down the line (like
through the DH Now blog post I have on my CV), there will be some
interesting considerations of the project and its conclusion. I'd love to
write a blog post on it if nothing else.

On Wed, Apr 27, 2016 at 8:47 AM, Eric Rochester notifications@github.com
wrote:

> Closed #277 https://github.com/scholarslab/ivanhoe/issues/277.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/scholarslab/ivanhoe/issues/277#event-642838161

## 

Jennifer Grayburn, Ph.D.
History of Art and Architecture
McIntire Department of Art
University of Virginia
jng3au@virginia.edu

**Comment by erochest** [comment]
They would have seen a notice that it's no longer accessible. This would not apply to the Ivanhoe project itself, only the sample games that are on the staging server, which isn't even running the latest version of the plugin. Ivanhoe itself would still be available for download.

That said, at this point, nothing should change. Everything will stay up, but the staging site probably won't be useful for creating new games, but I don't believe that was happening, anyway.
