### ISSUE TITLE
Make ivanhoe_move_link function work for both responses and new moves

### ISSUE THREAD

**Issue by vai2fc** [scholarslab/ivanhoe#86]
The ivanhoe_move_link function currently works for responses to moves. We need to figure out how to make it work for  independent moves, too.

**Comment by csbailey5t** [comment]
This is effectively handled in cdb82c57e6dab794d85504cc165c0d41a0d16e05 and the surrounding commits, where we implement multi-source responses. Rather than having separate buttons for responding and making an independent move, we have a single button whose text is changed depending on whether there are any sources added to the source array.
